name: Update PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set footer
        run: |
          FOOTER='<!-- my-footer -->'
          echo "FOOTER=$FOOTER" >> $GITHUB_ENV
      - name: Find existing comment
        id: existing_comment

        run: |
          COMMENT_ID=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments | jq -r --arg footer "$FOOTER" 'map(select(.body | contains($footer)) | .id) | first // ""' | head -n1)

          if [[ -n "$COMMENT_ID" ]]; then
            echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV
          fi
          echo $COMMENT_ID

      - name: Update existing comment
        if: env.COMMENT_ID != ''
        run: |
          gh api --method PATCH repos/${{ github.repository }}/issues/comments/"$COMMENT_ID" \
            -f body="
            test (updated) 
            ${FOOTER}
            "

      - name: Post new comment if none exists
        if: env.COMMENT_ID == ''
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "
          test
          ${FOOTER}
          "
