name: Update PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_comment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Set footer
        run: |
          echo "FOOTER=\n<!-- my-invisible-footer -->" >> $GITHUB_ENV
      - name: Find existing comment
        id: existing_comment

        run: |
          COMMENT_ID=$(gh api repos/${{ github.repository }}/issues/${PR_NUMBER}/comments --jq \
            '.[] | select(.body | contains(${FOOTER})) | .id' | head -n1)

          if [[ -n "$COMMENT_ID" ]]; then
            echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV
          fi

      - name: Update existing comment
        if: env.COMMENT_ID != ''
        run: |
          gh api --method PATCH repos/${{ github.repository }}/issues/comments/${COMMENT_ID} \
            -f body="test ${FOOTER}"

      - name: Post new comment if none exists
        if: env.COMMENT_ID == ''
        run: |
          gh pr comment $PR_NUMBER --body "test (updated) ${FOOTER}"
